version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: medicitas_nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  squid:
    image: ubuntu/squid:latest
    container_name: medicitas_squid
    ports:
      - "3128:3128"
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf:ro
    restart: always
